development:
  adapter: postgresql
  encoding: utf8
  url: "postgres://maxc@localhost/sample_blog_development"
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: sample_blog_test
  pool: 5

production:
  adapter: postgresql
  pool: 12
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
